# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_example',
                'doc_host': 'https://ravennaro.github.io',
                'git_url': 'https://github.com/ravennaro/nbdev_example',
                'lib_path': 'nbdev_example'},
  'syms': { 'nbdev_example.card': { 'nbdev_example.card.Card': ('cards.html#card', 'nbdev_example/card.py'),
                                    'nbdev_example.card.Card.__eq__': ('cards.html#card.__eq__', 'nbdev_example/card.py'),
                                    'nbdev_example.card.Card.__gt__': ('cards.html#card.__gt__', 'nbdev_example/card.py'),
                                    'nbdev_example.card.Card.__init__': ('cards.html#card.__init__', 'nbdev_example/card.py'),
                                    'nbdev_example.card.Card.__lt__': ('cards.html#card.__lt__', 'nbdev_example/card.py'),
                                    'nbdev_example.card.Card.__str__': ('cards.html#card.__str__', 'nbdev_example/card.py')},
            'nbdev_example.core': { 'nbdev_example.core.Deck': ('deckc.html#deck', 'nbdev_example/core.py'),
                                    'nbdev_example.core.Deck.__contains__': ('deckc.html#deck.__contains__', 'nbdev_example/core.py'),
                                    'nbdev_example.core.Deck.__init__': ('deckc.html#deck.__init__', 'nbdev_example/core.py'),
                                    'nbdev_example.core.Deck.__len__': ('deckc.html#deck.__len__', 'nbdev_example/core.py'),
                                    'nbdev_example.core.Deck.__str__': ('deckc.html#deck.__str__', 'nbdev_example/core.py')}}}
