# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_deckc.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../nbs/01_deckc.ipynb 2
from .card import *

# %% ../nbs/01_deckc.ipynb 4
class Deck:
    def __init__(self): 
        self.cards = [Card(s, r) for s in range(4) for r in range (1,14)]
    def __len__(self):
        return len(self.cards)
    def __str__(self): 
        return '; '.join(map(str, self.cards))
    def __contains__(self, card):
        return card in self.cards
    __repr__ = __str__
